#!/usr/bin/env python3
"""Extract the text off the REVL workout-screenshot libraries into one Markdown file.

Input  : the two screenshot folders on disk (git-ignored, local only):
             REVL Block 1 2026/
             REVL Block 2 programming 2026/
         Each has 13 phase-week subfolders (Volume Wk 1 .. Rebuild Wk 3) with one
         PNG per session, named "<day> <session>.png"
         (e.g. "Volume Wk 1/monday perform total.png").

Output : source/revl_raw_data.md  -- every screenshot's OCR text, grouped
         block -> phase-week -> session, plus a coverage summary. This is the
         raw evidence layer behind references/revl-class-integration.md.

OCR    : rapidocr-onnxruntime (pure-Python, CPU). Per-image results are cached
         under source/.revl_ocr_cache/ so re-runs are fast.

Usage  : python source/extract_revl.py                # full run
         python source/extract_revl.py --limit 6      # quick smoke test
         python source/extract_revl.py --blocks 1     # one block only

NOTE   : OCR of stylised poster text is imperfect. Downstream docs must treat
         this output as approximate evidence, never as verbatim fact.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BLOCK_DIRS = {
    1: REPO / "REVL Block 1 2026",
    2: REPO / "REVL Block 2 programming 2026",
}
OUT = Path(__file__).resolve().parent / "revl_raw_data.md"
CACHE = Path(__file__).resolve().parent / ".revl_ocr_cache"

PHASE_ORDER = [
    "Volume Wk 1", "Volume Wk 2", "Volume Wk 3",
    "Build Wk 1", "Build Wk 2", "Build Wk 3",
    "Deload Wk 1",
    "Peak Wk 1", "Peak Wk 2", "Peak Wk 3",
    "Rebuild Wk 1", "Rebuild Wk 2", "Rebuild Wk 3",
]
DAY_ORDER = ["monday", "tuesday", "wednesday", "thursday", "friday",
             "saturday", "sunday", "qld", "albury", "coaches"]


def phase_week_num(folder: str) -> int:
    """Volume Wk 1 -> 1, Build Wk 1 -> 4, Deload Wk 1 -> 7, Peak Wk 1 -> 8, ..."""
    try:
        return PHASE_ORDER.index(folder) + 1
    except ValueError:
        return 99


def day_key(fname: str):
    stem = fname.lower().rsplit(".", 1)[0]
    first = stem.split(" ")[0]
    di = DAY_ORDER.index(first) if first in DAY_ORDER else 50
    return (di, stem)


_ocr = None


def get_ocr():
    global _ocr
    if _ocr is None:
        from rapidocr_onnxruntime import RapidOCR
        _ocr = RapidOCR()
    return _ocr


def ocr_image(path: Path) -> str:
    CACHE.mkdir(exist_ok=True)
    key = hashlib.md5(str(path.relative_to(REPO)).encode()).hexdigest()[:16]
    cached = CACHE / f"{key}.txt"
    if cached.exists() and cached.stat().st_mtime >= path.stat().st_mtime:
        return cached.read_text(encoding="utf-8")
    try:
        result, _ = get_ocr()(str(path))
        text = "\n".join(line[1] for line in result) if result else ""
    except Exception as exc:  # noqa: BLE001
        text = f"__OCR_ERROR__ {exc}"
    cached.write_text(text, encoding="utf-8")
    return text


def tidy(text: str) -> str:
    lines = [ln.rstrip() for ln in text.splitlines()]
    lines = [ln for ln in lines if ln.strip()]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--limit", type=int, default=0, help="only OCR the first N images (smoke test)")
    ap.add_argument("--blocks", type=int, nargs="+", choices=[1, 2], default=[1, 2])
    args = ap.parse_args(argv)

    missing = [str(BLOCK_DIRS[b]) for b in args.blocks if not BLOCK_DIRS[b].is_dir()]
    if missing:
        print("ERROR: screenshot folder(s) not found:\n  " + "\n  ".join(missing), file=sys.stderr)
        print("These folders are git-ignored; they must be present locally to extract.", file=sys.stderr)
        return 1

    out: list[str] = []
    out.append("# REVL programming — raw extracted screenshot data\n")
    out.append("Auto-generated by `source/extract_revl.py` (rapidocr-onnxruntime OCR of the")
    out.append("screenshot libraries in `REVL Block 1 2026/` and `REVL Block 2 programming 2026/`).\n")
    out.append("> **Evidence quality.** These posters use heavily stylised type over photos.")
    out.append("> OCR loses word spacing, misreads numbers, and drops small print. Downstream")
    out.append("> documents must treat this as *approximate* evidence — never quote a specific")
    out.append("> load, rep count, or percentage from here as fact.\n")

    total = 0
    errors = 0
    processed = 0
    per_block_counts = {}

    for b in args.blocks:
        root = BLOCK_DIRS[b]
        out.append(f"\n---\n\n# Block {b}  (`{root.name}/`)\n")
        folders = sorted((d for d in root.iterdir() if d.is_dir()),
                         key=lambda d: phase_week_num(d.name))
        block_imgs = 0
        for folder in folders:
            wknum = phase_week_num(folder.name)
            out.append(f"\n## Block {b} — {folder.name}  (programme week {wknum})\n")
            pngs = sorted(folder.glob("*.png"), key=lambda p: day_key(p.name))
            for png in pngs:
                total += 1
                block_imgs += 1
                if args.limit and processed >= args.limit:
                    out.append(f"### {png.stem}\n\n_(skipped: --limit {args.limit})_\n")
                    continue
                processed += 1
                text = tidy(ocr_image(png))
                if text.startswith("__OCR_ERROR__"):
                    errors += 1
                out.append(f"### {png.stem}")
                out.append(f"`{png.relative_to(REPO)}`\n")
                out.append("```")
                out.append(text if text else "(no text detected)")
                out.append("```\n")
                if processed % 20 == 0:
                    print(f"  ...{processed} images OCR'd", file=sys.stderr)
        per_block_counts[b] = block_imgs

    summary = [
        "\n---\n\n## Extraction summary\n",
        f"- Blocks extracted: {', '.join(str(b) for b in args.blocks)}",
        *[f"- Block {b}: {per_block_counts[b]} screenshots" for b in args.blocks],
        f"- Total screenshots: {total}",
        f"- OCR'd this run: {processed}" + (f"  (--limit {args.limit})" if args.limit else ""),
        f"- OCR errors: {errors}",
        f"- Cache: `{CACHE.relative_to(REPO)}/`",
        "",
    ]
    out[4:4] = []  # keep header order; summary goes at the end
    out += summary

    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}  ({OUT.stat().st_size // 1024} KB, "
          f"{total} screenshots, {processed} OCR'd, {errors} errors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
